name: go-test

on:
  - push

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -v ./...
